using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Clicalo.Generators.Localization;

/// <summary>
/// Turns a <see cref="LocalizationModel"/> into C#: the <c>MessageKey</c> type, the static class <c>L</c> with one
/// member per key, and <c>MessageCatalog</c> with the key metadata. Output is deterministic: it only depends on
/// the model, always uses <c>\n</c> and never includes paths, dates or versions of the build.
/// </summary>
internal static class LocalizationEmitter
{
    public const string Namespace = "Clicalo.Domain.Messages";

    private const string GeneratedCode =
        "[global::System.CodeDom.Compiler.GeneratedCode(\"Clicalo.Generators.LocalizationGenerator\", \"1.0.0\")]";

    private const string ExcludeFromCoverage =
        "[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = \"Generated from data/i18n.\")]";

    private static readonly ImmutableArray<string> CSharpKeywords =
    [
        "abstract",
        "as",
        "base",
        "bool",
        "break",
        "byte",
        "case",
        "catch",
        "char",
        "checked",
        "class",
        "const",
        "continue",
        "decimal",
        "default",
        "delegate",
        "do",
        "double",
        "else",
        "enum",
        "event",
        "explicit",
        "extern",
        "false",
        "finally",
        "fixed",
        "float",
        "for",
        "foreach",
        "goto",
        "if",
        "implicit",
        "in",
        "int",
        "interface",
        "internal",
        "is",
        "lock",
        "long",
        "namespace",
        "new",
        "null",
        "object",
        "operator",
        "out",
        "override",
        "params",
        "private",
        "protected",
        "public",
        "readonly",
        "ref",
        "return",
        "sbyte",
        "sealed",
        "short",
        "sizeof",
        "stackalloc",
        "static",
        "string",
        "struct",
        "switch",
        "this",
        "throw",
        "true",
        "try",
        "typeof",
        "uint",
        "ulong",
        "unchecked",
        "unsafe",
        "ushort",
        "using",
        "virtual",
        "void",
        "volatile",
        "while",
    ];

    /// <summary>Generates the sources for <paramref name="model"/>. <c>MessageKey</c> is always emitted.</summary>
    public static ImmutableArray<GeneratedSource> Emit(LocalizationModel model) =>
        [
            new(Namespace + ".MessageKey.g.cs", EmitMessageKey()),
            new(Namespace + ".L.g.cs", EmitMessages(model)),
            new(Namespace + ".MessageCatalog.g.cs", EmitCatalog(model)),
        ];

    private static StringBuilder Header()
    {
        var sb = new StringBuilder();
        sb.Append("// <auto-generated/>\n");
        sb.Append("// Generated by Clicalo.Generators (LocalizationGenerator) from data/i18n.\n");
        sb.Append("// Do not edit: change the JSON files and rebuild (docs/guides/i18n.md).\n");
        sb.Append("#nullable enable\n\n");
        sb.Append("namespace ").Append(Namespace).Append(";\n\n");
        return sb;
    }

    private static string EmitMessageKey()
    {
        var sb = Header();
        sb.Append("/// <summary>\n");
        sb.Append(
            "/// Stable identifier of a localized text of <c>data/i18n</c>: the original key of the design handoff,\n"
        );
        sb.Append("/// without plural suffix (for example <c>migT</c>).\n");
        sb.Append("/// </summary>\n");
        sb.Append("/// <param name=\"Value\">The key as written in <c>data/i18n</c>.</param>\n");
        sb.Append(GeneratedCode).Append('\n');
        sb.Append("public readonly record struct MessageKey(string Value)\n");
        sb.Append("{\n");
        sb.Append("    /// <summary>Returns the key itself.</summary>\n");
        sb.Append("    public override string ToString() => Value;\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    private static string EmitMessages(LocalizationModel model)
    {
        var sb = Header();
        sb.Append("/// <summary>\n");
        sb.Append(
            "/// Typed access to every text of <c>data/i18n</c>: one member per key, documented with the text of the\n"
        );
        sb.Append(
            "/// default language. Members without placeholders are cached messages; members with placeholders are\n"
        );
        sb.Append(
            "/// methods whose parameters are the expected arguments. Format them with <c>ILocalizer</c>.\n"
        );
        sb.Append("/// </summary>\n");
        sb.Append(GeneratedCode).Append('\n');
        sb.Append(ExcludeFromCoverage).Append('\n');
        sb.Append("public static class " + KeyNaming.MessagesClass + "\n");
        sb.Append("{\n");
        var first = true;
        foreach (var message in model.Messages)
        {
            if (!first)
            {
                sb.Append('\n');
            }

            first = false;
            AppendMember(sb, message);
        }

        sb.Append("}\n");
        return sb.ToString();
    }

    private static void AppendMember(StringBuilder sb, MessageDefinition message)
    {
        var forms = message.DefaultForms;
        if (forms.Length == 1 && forms[0].Category is null && forms[0].Text.IndexOf('\n') < 0)
        {
            sb.Append("    /// <summary>").Append(EscapeXml(forms[0].Text)).Append("</summary>\n");
        }
        else
        {
            sb.Append("    /// <summary>\n");
            foreach (var form in forms)
            {
                var text = EscapeXml(form.Text);
                AppendDocLines(
                    sb,
                    form.Category is null
                        ? text
                        : "<para><c>" + form.Category + "</c>: " + text + "</para>"
                );
            }

            sb.Append("    /// </summary>\n");
        }

        sb.Append("    /// <remarks>Key <c>").Append(message.Key).Append("</c>");
        if (message.IsPlural)
        {
            sb.Append("; plural family selected by <c>")
                .Append(PluralCategories.SelectorArgument)
                .Append("</c>");
        }

        sb.Append(".</remarks>\n");
        foreach (var argument in message.Arguments)
        {
            sb.Append("    /// <param name=\"").Append(argument.Name).Append("\">");
            sb.Append(EscapeXml(argument.Description)).Append("</param>\n");
        }

        var key = "new MessageKey(\"" + message.Key + "\")";
        if (message.Arguments.IsEmpty)
        {
            sb.Append("    public static Message ").Append(message.MemberName);
            sb.Append(" { get; } = new(").Append(key).Append(");\n");
            return;
        }

        sb.Append("    public static Message ").Append(message.MemberName).Append('(');
        sb.Append(
            string.Join(
                ", ",
                message.Arguments.Select(static a =>
                    ParameterType(a.Type) + " " + Identifier(a.Name)
                )
            )
        );
        sb.Append(") =>\n");
        sb.Append("        new(\n");
        sb.Append("            ").Append(key);
        foreach (var argument in message.Arguments)
        {
            sb.Append(",\n            MessageArgument.").Append(DomainTypeName(argument.Type));
            sb.Append("(\"")
                .Append(argument.Name)
                .Append("\", ")
                .Append(Identifier(argument.Name))
                .Append(')');
        }

        sb.Append("\n        );\n");
    }

    private static string EmitCatalog(LocalizationModel model)
    {
        var sb = Header();
        sb.Append(
            "/// <summary>Metadata of every key of <c>data/i18n</c>, to validate language packs and data references.</summary>\n"
        );
        sb.Append(GeneratedCode).Append('\n');
        sb.Append(ExcludeFromCoverage).Append('\n');
        sb.Append("public static class MessageCatalog\n");
        sb.Append("{\n");
        sb.Append(
            "    private static readonly global::System.Lazy<global::System.Collections.Frozen.FrozenDictionary<string, MessageDescriptor>> ByKey =\n"
        );
        sb.Append(
            "        new(static () => global::System.Collections.Frozen.FrozenDictionary.ToFrozenDictionary(\n"
        );
        sb.Append("            All,\n");
        sb.Append("            static d => d.Key.Value,\n");
        sb.Append("            global::System.StringComparer.Ordinal\n");
        sb.Append("        ));\n\n");
        sb.Append(
            "    /// <summary>Every key, in the order of the default language file.</summary>\n"
        );
        sb.Append(
            "    public static global::System.Collections.Immutable.ImmutableArray<MessageDescriptor> All { get; } =\n"
        );
        sb.Append("    [\n");
        foreach (var message in model.Messages)
        {
            sb.Append("        new(new MessageKey(\"").Append(message.Key).Append("\"), ");
            sb.Append(message.IsPlural ? "true" : "false");
            foreach (var argument in message.Arguments)
            {
                sb.Append(", new MessageParameter(\"")
                    .Append(argument.Name)
                    .Append("\", MessageArgumentType.");
                sb.Append(DomainTypeName(argument.Type)).Append(')');
            }

            sb.Append("),\n");
        }

        sb.Append("    ];\n\n");
        sb.Append(
            "    /// <summary>Finds the descriptor of <paramref name=\"key\"/> (ordinal comparison).</summary>\n"
        );
        sb.Append("    public static bool TryGet(\n");
        sb.Append("        string key,\n");
        sb.Append(
            "        [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out MessageDescriptor? descriptor\n"
        );
        sb.Append("    ) => ByKey.Value.TryGetValue(key, out descriptor);\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    private static string ParameterType(PlaceholderType type) =>
        type switch
        {
            PlaceholderType.Integer => "long",
            PlaceholderType.Number => "decimal",
            _ => "MessageText",
        };

    /// <summary>Member name shared by <c>MessageArgument</c> factories and <c>MessageArgumentType</c>.</summary>
    private static string DomainTypeName(PlaceholderType type) =>
        type switch
        {
            PlaceholderType.Integer => "WholeNumber",
            PlaceholderType.Number => "DecimalNumber",
            _ => "Text",
        };

    private static string Identifier(string name) =>
        CSharpKeywords.Contains(name, StringComparer.Ordinal) ? "@" + name : name;

    private static void AppendDocLines(StringBuilder sb, string text)
    {
        foreach (var line in text.Replace("\r\n", "\n").Split('\n'))
        {
            sb.Append("    /// ").Append(line.TrimEnd()).Append('\n');
        }
    }

    private static string EscapeXml(string text) =>
        text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}
