using System.Text;

namespace Clicalo.Generators.Catalogs;

/// <summary>
/// Minimal indented writer for generated C#. Always uses LF line endings so the output is byte-identical on
/// every machine (deterministic builds).
/// </summary>
internal sealed class SourceWriter
{
    private readonly StringBuilder _builder = new();
    private int _indent;

    /// <summary>Starts a generated file: header, nullable context and file-scoped namespace.</summary>
    public static SourceWriter ForFile(string namespaceName, string sourceFile)
    {
        var writer = new SourceWriter();
        writer.Line("// <auto-generated>");
        writer.Line(
            "//   Generated by Clicalo.Generators (CatalogGenerator) from " + sourceFile + "."
        );
        writer.Line("//   Do not edit: change the data file and rebuild.");
        writer.Line("// </auto-generated>");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line("namespace " + namespaceName + ";");
        writer.Line();
        return writer;
    }

    public SourceWriter Line(string text = "")
    {
        if (text.Length > 0)
        {
            _builder.Append(' ', _indent * 4);
            _builder.Append(text);
        }

        _builder.Append('\n');
        return this;
    }

    /// <summary>Writes an XML documentation summary with the text escaped.</summary>
    public SourceWriter Summary(string text) =>
        Line("/// <summary>" + EscapeXml(text) + "</summary>");

    /// <summary>Writes the attribute that marks a type as generated.</summary>
    public SourceWriter GeneratedCode() =>
        Line(
            "[global::System.CodeDom.Compiler.GeneratedCode(\"Clicalo.Generators.CatalogGenerator\", \"1.0\")]"
        );

    public SourceWriter Open(string declaration)
    {
        Line(declaration);
        Line("{");
        _indent++;
        return this;
    }

    public SourceWriter Close(string suffix = "")
    {
        _indent--;
        Line("}" + suffix);
        return this;
    }

    public override string ToString() => _builder.ToString();

    /// <summary>Escapes text for XML documentation comments.</summary>
    public static string EscapeXml(string text) =>
        text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;").Replace("\n", " ");

    /// <summary>Escapes text for a C# regular string literal.</summary>
    public static string EscapeString(string text)
    {
        var builder = new StringBuilder(text.Length + 2);
        foreach (var c in text)
        {
            switch (c)
            {
                case '\\':
                    builder.Append("\\\\");
                    break;
                case '"':
                    builder.Append("\\\"");
                    break;
                case '\n':
                    builder.Append("\\n");
                    break;
                case '\r':
                    builder.Append("\\r");
                    break;
                case '\t':
                    builder.Append("\\t");
                    break;
                default:
                    if (c < ' ' || char.IsSurrogate(c) || c > '~')
                    {
                        builder
                            .Append("\\u")
                            .Append(
                                ((int)c).ToString(
                                    "x4",
                                    System.Globalization.CultureInfo.InvariantCulture
                                )
                            );
                    }
                    else
                    {
                        builder.Append(c);
                    }

                    break;
            }
        }

        return builder.ToString();
    }
}
