using System.Collections.Immutable;
using System.Reflection;
using ArchUnitNET.Loader;

namespace Clicalo.Architecture.Tests.Support;

/// <summary>The product assemblies (src/), loaded once for every rule, and their zones.</summary>
internal static class Product
{
    private static readonly Lazy<LoadedArchitecture> LazyArchitecture = new(Load);

    /// <summary>Project name to assembly name for every product project (Clicalo.App builds Clicalo.exe).</summary>
    public static ImmutableSortedDictionary<string, string> AssemblyOfProject { get; } =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Clicalo.App"] = "Clicalo",
            ["Clicalo.Application"] = "Clicalo.Application",
            ["Clicalo.Domain"] = "Clicalo.Domain",
            ["Clicalo.Infrastructure"] = "Clicalo.Infrastructure",
            ["Clicalo.Launcher"] = "Clicalo.Launcher",
            ["Clicalo.Platform.Core"] = "Clicalo.Platform.Core",
            ["Clicalo.Platform.Windows"] = "Clicalo.Platform.Windows",
            ["Clicalo.Presentation"] = "Clicalo.Presentation",
            ["Clicalo.Sentinel"] = "Clicalo.Sentinel",
            ["Clicalo.UI.Wpf"] = "Clicalo.UI.Wpf",
        }.ToImmutableSortedDictionary(StringComparer.Ordinal);

    /// <summary>Every product assembly, loaded with ArchUnitNET.</summary>
    public static LoadedArchitecture Architecture => LazyArchitecture.Value;

    public static Zone Domain { get; } = Zone.Assembly("Clicalo.Domain");

    public static Zone Application { get; } = Zone.Assembly("Clicalo.Application");

    public static Zone Presentation { get; } = Zone.Assembly("Clicalo.Presentation");

    public static Zone UiWpf { get; } = Zone.Assembly("Clicalo.UI.Wpf");

    public static Zone PlatformCore { get; } = Zone.Assembly("Clicalo.Platform.Core");

    public static Zone PlatformWindows { get; } = Zone.Assembly("Clicalo.Platform.Windows");

    public static Zone Infrastructure { get; } = Zone.Assembly("Clicalo.Infrastructure");

    public static Zone App { get; } = Zone.Assembly("Clicalo");

    public static Zone Sentinel { get; } = Zone.Assembly("Clicalo.Sentinel");

    public static Zone Launcher { get; } = Zone.Assembly("Clicalo.Launcher");

    /// <summary>Every product type.</summary>
    public static Zone All { get; } =
        Zone.AnyOf("the product", [.. AssemblyOfProject.Values.Select(Zone.Assembly)]);

    /// <summary>Win32 interop generated by CsWin32 into the product assemblies (namespace <c>Windows.Win32</c>).</summary>
    public static Zone GeneratedInterop { get; } = Zone.Namespace("Windows.Win32");

    /// <summary>Every product type written by hand or by our own generators (the CsWin32 interop excluded).</summary>
    public static Zone Code { get; } = All.Except(GeneratedInterop);

    /// <summary>The zone of a product project, by project name.</summary>
    public static Zone OfProject(string projectName) =>
        Zone.Assembly(AssemblyOfProject[projectName]);

    private static LoadedArchitecture Load()
    {
        var assemblies = AssemblyOfProject
            .Values.Select(name => System.Reflection.Assembly.Load(new AssemblyName(name)))
            .ToArray();
        return new ArchLoader().LoadAssemblies(assemblies).Build();
    }
}
