using System.Collections.Frozen;

namespace Clicalo.Domain.Execution.Internal;

/// <summary>
/// The virtual key, set-1 scan code and extended flag of every fixed key of the catalog, exactly as
/// <c>data/catalogs/keys.win32.json</c> gives them for the reference layout 00000409 (blueprint §7.7: fixed keys take
/// <c>scan</c> and <c>extended</c> from that table in both modes, because <c>MapVirtualKeyEx</c> gets the navigation
/// keys, Print Screen and Pause wrong). Character keys (<c>char:</c>) are not here: they come from the foreground
/// layout. <c>Win32FixedKeysTests</c> compares this table with the JSON entry by entry, so they cannot drift apart;
/// it goes away when the catalog generator emits it (a frozen path in M2).
/// </summary>
internal static class Win32FixedKeys
{
    /// <summary>The table, by canonical key id.</summary>
    public static FrozenDictionary<string, FixedKey> ById { get; } =
        new Dictionary<string, FixedKey>(StringComparer.Ordinal)
        {
            ["ctrl"] = new(0xA2, 0x1D, false, false),
            ["alt"] = new(0xA4, 0x38, false, false),
            ["shift"] = new(0xA0, 0x2A, false, false),
            ["win"] = new(0x5B, 0x5B, true, false),
            ["lctrl"] = new(0xA2, 0x1D, false, false),
            ["rctrl"] = new(0xA3, 0x1D, true, false),
            ["lshift"] = new(0xA0, 0x2A, false, false),
            ["rshift"] = new(0xA1, 0x36, false, false),
            ["lalt"] = new(0xA4, 0x38, false, false),
            ["altgr"] = new(0xA5, 0x38, true, false),
            ["rwin"] = new(0x5C, 0x5C, true, false),
            ["a"] = new(0x41, 0x1E, false, false),
            ["b"] = new(0x42, 0x30, false, false),
            ["c"] = new(0x43, 0x2E, false, false),
            ["d"] = new(0x44, 0x20, false, false),
            ["e"] = new(0x45, 0x12, false, false),
            ["f"] = new(0x46, 0x21, false, false),
            ["g"] = new(0x47, 0x22, false, false),
            ["h"] = new(0x48, 0x23, false, false),
            ["i"] = new(0x49, 0x17, false, false),
            ["j"] = new(0x4A, 0x24, false, false),
            ["k"] = new(0x4B, 0x25, false, false),
            ["l"] = new(0x4C, 0x26, false, false),
            ["m"] = new(0x4D, 0x32, false, false),
            ["n"] = new(0x4E, 0x31, false, false),
            ["o"] = new(0x4F, 0x18, false, false),
            ["p"] = new(0x50, 0x19, false, false),
            ["q"] = new(0x51, 0x10, false, false),
            ["r"] = new(0x52, 0x13, false, false),
            ["s"] = new(0x53, 0x1F, false, false),
            ["t"] = new(0x54, 0x14, false, false),
            ["u"] = new(0x55, 0x16, false, false),
            ["v"] = new(0x56, 0x2F, false, false),
            ["w"] = new(0x57, 0x11, false, false),
            ["x"] = new(0x58, 0x2D, false, false),
            ["y"] = new(0x59, 0x15, false, false),
            ["z"] = new(0x5A, 0x2C, false, false),
            ["1"] = new(0x31, 0x02, false, false),
            ["2"] = new(0x32, 0x03, false, false),
            ["3"] = new(0x33, 0x04, false, false),
            ["4"] = new(0x34, 0x05, false, false),
            ["5"] = new(0x35, 0x06, false, false),
            ["6"] = new(0x36, 0x07, false, false),
            ["7"] = new(0x37, 0x08, false, false),
            ["8"] = new(0x38, 0x09, false, false),
            ["9"] = new(0x39, 0x0A, false, false),
            ["0"] = new(0x30, 0x0B, false, false),
            ["f1"] = new(0x70, 0x3B, false, false),
            ["f2"] = new(0x71, 0x3C, false, false),
            ["f3"] = new(0x72, 0x3D, false, false),
            ["f4"] = new(0x73, 0x3E, false, false),
            ["f5"] = new(0x74, 0x3F, false, false),
            ["f6"] = new(0x75, 0x40, false, false),
            ["f7"] = new(0x76, 0x41, false, false),
            ["f8"] = new(0x77, 0x42, false, false),
            ["f9"] = new(0x78, 0x43, false, false),
            ["f10"] = new(0x79, 0x44, false, false),
            ["f11"] = new(0x7A, 0x57, false, false),
            ["f12"] = new(0x7B, 0x58, false, false),
            ["enter"] = new(0x0D, 0x1C, false, false),
            ["tab"] = new(0x09, 0x0F, false, false),
            ["esc"] = new(0x1B, 0x01, false, false),
            ["space"] = new(0x20, 0x39, false, false),
            ["delete"] = new(0x2E, 0x53, true, false),
            ["backspace"] = new(0x08, 0x0E, false, false),
            ["home"] = new(0x24, 0x47, true, false),
            ["end"] = new(0x23, 0x4F, true, false),
            ["pageup"] = new(0x21, 0x49, true, false),
            ["pagedown"] = new(0x22, 0x51, true, false),
            ["left"] = new(0x25, 0x4B, true, false),
            ["right"] = new(0x27, 0x4D, true, false),
            ["up"] = new(0x26, 0x48, true, false),
            ["down"] = new(0x28, 0x50, true, false),
            ["printscreen"] = new(0x2C, 0x37, true, false),
            ["menu"] = new(0x5D, 0x5D, true, false),
            ["num.0"] = new(0x60, 0x52, false, false),
            ["num.1"] = new(0x61, 0x4F, false, false),
            ["num.2"] = new(0x62, 0x50, false, false),
            ["num.3"] = new(0x63, 0x51, false, false),
            ["num.4"] = new(0x64, 0x4B, false, false),
            ["num.5"] = new(0x65, 0x4C, false, false),
            ["num.6"] = new(0x66, 0x4D, false, false),
            ["num.7"] = new(0x67, 0x47, false, false),
            ["num.8"] = new(0x68, 0x48, false, false),
            ["num.9"] = new(0x69, 0x49, false, false),
            ["num.add"] = new(0x6B, 0x4E, false, false),
            ["num.subtract"] = new(0x6D, 0x4A, false, false),
            ["num.multiply"] = new(0x6A, 0x37, false, false),
            ["num.divide"] = new(0x6F, 0x35, true, false),
            ["num.decimal"] = new(0x6E, 0x53, false, false),
            ["num.enter"] = new(0x0D, 0x1C, true, false),
            ["numlock"] = new(0x90, 0x45, false, false),
            ["volume.up"] = new(0xAF, 0x30, true, false),
            ["volume.down"] = new(0xAE, 0x2E, true, false),
            ["volume.mute"] = new(0xAD, 0x20, true, false),
            ["media.playpause"] = new(0xB3, 0x22, true, false),
            ["media.next"] = new(0xB0, 0x19, true, false),
            ["media.previous"] = new(0xB1, 0x10, true, false),
            ["media.stop"] = new(0xB2, 0x24, true, false),
            ["launch.calculator"] = new(0xB7, 0x21, true, false),
            ["launch.browser"] = new(0xAC, 0x32, true, false),
            ["launch.mail"] = new(0xB4, 0x6C, true, false),
            ["capslock"] = new(0x14, 0x3A, false, false),
            ["insert"] = new(0x2D, 0x52, true, false),
            ["pause"] = new(0x13, 0x1D, false, true),
            ["scrolllock"] = new(0x91, 0x46, false, false),
            ["f13"] = new(0x7C, 0x64, false, false),
            ["f14"] = new(0x7D, 0x65, false, false),
            ["f15"] = new(0x7E, 0x66, false, false),
            ["f16"] = new(0x7F, 0x67, false, false),
            ["f17"] = new(0x80, 0x68, false, false),
            ["f18"] = new(0x81, 0x69, false, false),
            ["f19"] = new(0x82, 0x6A, false, false),
            ["f20"] = new(0x83, 0x6B, false, false),
            ["f21"] = new(0x84, 0x6C, false, false),
            ["f22"] = new(0x85, 0x6D, false, false),
            ["f23"] = new(0x86, 0x6E, false, false),
            ["f24"] = new(0x87, 0x76, false, false),
        }.ToFrozenDictionary(StringComparer.Ordinal);
}
